---
layout: post
title: NBA Stats in R
excerpt_separator: <!--more-->
output:
  html_document:
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T)
```

```{r}
library(magrittr)
library(tidyverse)
if (!require(nbastatR))
  remotes::install_github("abresler/nbastatR")
library(nbastatR)
library(plotly)
library(rvest)
library(RSelenium) # start a server with utility function
library(seleniumPipes)

nbastatR::teams_players_stats(
  seasons = 2021,
  types = c("player"),
  tables = "general",
  measures = "Advanced",
  assign_to_environment = TRUE
)

url = 'https://projects.fivethirtyeight.com/nba-player-ratings/'
xpath = '//*[@id="luka-doncic-2021"]/td[15]'

#start server
remDr <- remoteDriver(
  remoteServerAddr = "localhost",
  port = 4444L,
  browserName = "chrome"
)

remDr %>% go(url)
price <- remDr %>% getPageSource() %>% html_nodes(".price-amount") %>% html_text()

# raptor = 
  url %>% read_html() %>%
  html_elements(xpath = xpath) %>% 
  html_table()

stats = dataGeneralPlayers %>% 
  select(6,7,8,10,netrtg,pctUSG,pieRank,ratioPIE) %>%
  filter(gp > 36) %>% 
  arrange(desc(netrtg)) %>% 
  mutate(highlight = case_when(
    namePlayer == "Russell Westbrook"~TRUE,
    TRUE~FALSE))
ggplot(stats, aes(ratioPIE, pctUSG, color = highlight,
                  label=namePlayer)) +
  geom_point()
ggplotly()
```

